//
// Copyright (c) 2023 Vinnie Falco (vinnie.falco@gmail.com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at https://www.boost.org/LICENSE_1_0.txt)
//
// Official repository: https://github.com/cppalliance/http_proto
//

= Boost.HTTP.Proto

Boost.HTTP.Proto is a portable C++ library which provides containers and
algorithms which implement the HTTP/1.1 protocol, widely used to deliver content
on the Internet. It adheres strictly to the HTTP/1.1 RFC specification
(henceforth referred to as https://datatracker.ietf.org/doc/html/rfc9110[rfc9110,window=blank_]).

This library understands the grammars related to HTTP nessages and provides
functionality to validate, parse, examine, and modify messages.

== Features

== Requirements

The library requires a compiler supporting at least C++11.

Standard types such as `error_code` or `string_view` use their Boost equivalents.

== Tested Compilers

Boost.HTTP.Proto has been tested with the following compilers:

* clang:
* gcc:
* msvc:

and these architectures: x86, x64

We do not test and support gcc 8.0.1.

== Quality Assurance

The development infrastructure for the library includes these per-commit analyses:

* Coverage reports
* Compilation and tests on Drone.io and GitHub Actions
* Regular code audits for security

== ABNF

This documentation uses the Augmented
https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form[Backus-Naur Form,window=blank_]
(ABNF) notation of
https://datatracker.ietf.org/doc/html/rfc5234[rfc5234,window=blank_]
to specify particular grammars used by algorithms and containers.
While a complete understanding of the notation is not a requirement for using the
library, it may help for an understanding of how valid components of URLs are defined.
In particular, this is of interest to users who wish to compose parsing algorithms
using the combinators provided by the library.

== Acknowledgments

This library wouldn't be where it is today without the help of
https://github.com/pdimov[Peter Dimov,window=blank_]
for design advice and general assistance.
